<?php

namespace Database\Seeders;

use Database\Seeders\Traits\DisableForeignKeys;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    use DisableForeignKeys;

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->disableForeignKeys();
        DB::table('countries')->truncate();

        $countries = [
            [
                'id' => 1,
                'name' => 'Afghanistan',
                'code' => 'AF',
                'calling_code' => '93',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Albania',
                'code' => 'AL',
                'calling_code' => '355',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Algeria',
                'code' => 'DZ',
                'calling_code' => '213',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'American Samoa',
                'code' => 'AS',
                'calling_code' => '1 684',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Andorra',
                'code' => 'AD',
                'calling_code' => '376',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Angola',
                'code' => 'AO',
                'calling_code' => '244',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Anguilla',
                'code' => 'AI',
                'calling_code' => '1 264',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'Antigua and Barbuda',
                'code' => 'AG',
                'calling_code' => '1 286',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'Argentina',
                'code' => 'AR',
                'calling_code' => '54',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'name' => 'Armenia',
                'code' => 'AM',
                'calling_code' => '374',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'Aruba',
                'code' => 'AW',
                'calling_code' => '297',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'Australia',
                'code' => 'AU',
                'calling_code' => '61',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'name' => 'Austria',
                'code' => 'AT',
                'calling_code' => '43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'Azerbaijan',
                'code' => 'AZ',
                'calling_code' => '994',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'Bahamas',
                'code' => 'BS',
                'calling_code' => '1 242',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'Bahrain',
                'code' => 'BH',
                'calling_code' => '973',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'Bangladesh',
                'code' => 'BD',
                'calling_code' => '880',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'Barbados',
                'code' => 'BB',
                'calling_code' => '1 246',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 19,
                'name' => 'Belarus',
                'code' => 'BY',
                'calling_code' => '375',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'Belgium',
                'code' => 'BE',
                'calling_code' => '32',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 21,
                'name' => 'Belize',
                'code' => 'BZ',
                'calling_code' => '501',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 22,
                'name' => 'Benin',
                'code' => 'BJ',
                'calling_code' => '229',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 23,
                'name' => 'Bermuda',
                'code' => 'BM',
                'calling_code' => '1 441',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 24,
                'name' => 'Bhutan',
                'code' => 'BT',
                'calling_code' => '975',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 25,
                'name' => 'Plurinational State of Bolivia',
                'code' => 'BO',
                'calling_code' => '591',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'Bonaire',
                'code' => 'BQ',
                'calling_code' => '599 7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 27,
                'name' => 'Bosnia and Herzegovina',
                'code' => 'BA',
                'calling_code' => '387',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'name' => 'Botswana',
                'code' => 'BW',
                'calling_code' => '267',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'name' => 'Brazil',
                'code' => 'BR',
                'calling_code' => '55',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'name' => 'British Indian Ocean Territory',
                'code' => 'IO',
                'calling_code' => '246',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'name' => 'Brunei Darussalam',
                'code' => 'BN',
                'calling_code' => '673',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 32,
                'name' => 'Bulgaria',
                'code' => 'BG',
                'calling_code' => '359',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 33,
                'name' => 'Burkina Faso',
                'code' => 'BF',
                'calling_code' => '226',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 34,
                'name' => 'Burundi',
                'code' => 'BI',
                'calling_code' => '257',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 35,
                'name' => 'Cambodia',
                'code' => 'KH',
                'calling_code' => '855',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 36,
                'name' => 'Cameroon',
                'code' => 'CM',
                'calling_code' => '237',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 37,
                'name' => 'Canada',
                'code' => 'CA',
                'calling_code' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 38,
                'name' => 'Cape Verde',
                'code' => 'CV',
                'calling_code' => '238',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 39,
                'name' => 'Cayman Islands',
                'code' => 'KY',
                'calling_code' => '1 345',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 40,
                'name' => 'Central African Republic',
                'code' => 'CF',
                'calling_code' => '236',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 41,
                'name' => 'Chad',
                'code' => 'TD',
                'calling_code' => '235',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 42,
                'name' => 'Chile',
                'code' => 'CL',
                'calling_code' => '56',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 43,
                'name' => 'China',
                'code' => 'CN',
                'calling_code' => '86',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 44,
                'name' => 'Christmas Island',
                'code' => 'CX',
                'calling_code' => '61 89164',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 45,
                'name' => 'Cocos (Keeling) Islands',
                'code' => 'CC',
                'calling_code' => '61 89162',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 46,
                'name' => 'Colombia',
                'code' => 'CO',
                'calling_code' => '57',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 47,
                'name' => 'Comoros',
                'code' => 'KM',
                'calling_code' => '269',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 48,
                'name' => 'Congo',
                'code' => 'CG',
                'calling_code' => '242',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 49,
                'name' => 'Democratic Republic of the Congo',
                'code' => 'CD',
                'calling_code' => '243',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 50,
                'name' => 'Cook Islands',
                'code' => 'CK',
                'calling_code' => '682',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 51,
                'name' => 'Costa Rica',
                'code' => 'CR',
                'calling_code' => '506',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 52,
                'name' => 'Côte d\'Ivoire',
                'code' => 'CI',
                'calling_code' => '225',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 53,
                'name' => 'Croatia',
                'code' => 'HR',
                'calling_code' => '385',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 54,
                'name' => 'Cuba',
                'code' => 'CU',
                'calling_code' => '53',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 55,
                'name' => 'Curaçao',
                'code' => 'CW',
                'calling_code' => '599 9',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 56,
                'name' => 'Cyprus',
                'code' => 'CY',
                'calling_code' => '357',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 57,
                'name' => 'Czech Republic',
                'code' => 'CZ',
                'calling_code' => '420',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 58,
                'name' => 'Denmark',
                'code' => 'DK',
                'calling_code' => '45',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 59,
                'name' => 'Djibouti',
                'code' => 'DJ',
                'calling_code' => '253',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 60,
                'name' => 'Dominica',
                'code' => 'DM',
                'calling_code' => '1 767',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 61,
                'name' => 'Dominican Republic',
                'code' => 'DO',
                'calling_code' => '1 809',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 62,
                'name' => 'Ecuador',
                'code' => 'EC',
                'calling_code' => '593',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 63,
                'name' => 'Egypt',
                'code' => 'EG',
                'calling_code' => '20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 64,
                'name' => 'El Salvador',
                'code' => 'SV',
                'calling_code' => '503',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 65,
                'name' => 'Equatorial Guinea',
                'code' => 'GQ',
                'calling_code' => '240',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 66,
                'name' => 'Eritrea',
                'code' => 'ER',
                'calling_code' => '291',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 67,
                'name' => 'Estonia',
                'code' => 'EE',
                'calling_code' => '372',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 68,
                'name' => 'Ethiopia',
                'code' => 'ET',
                'calling_code' => '268',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 69,
                'name' => 'England',
                'code' => 'EL',
                'calling_code' => '44',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 70,
                'name' => 'Falkland Islands (Malvinas)',
                'code' => 'FK',
                'calling_code' => '500',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 71,
                'name' => 'Faroe Islands',
                'code' => 'FO',
                'calling_code' => '298',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 72,
                'name' => 'Fiji',
                'code' => 'FJ',
                'calling_code' => '679',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 73,
                'name' => 'Finland',
                'code' => 'FI',
                'calling_code' => '358',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 74,
                'name' => 'France',
                'code' => 'FR',
                'calling_code' => '33',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 75,
                'name' => 'French Polynesia',
                'code' => 'PF',
                'calling_code' => '689',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 76,
                'name' => 'Gabon',
                'code' => 'GA',
                'calling_code' => '241',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 77,
                'name' => 'Gambia',
                'code' => 'GM',
                'calling_code' => '220',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 78,
                'name' => 'Georgia',
                'code' => 'GE',
                'calling_code' => '995',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 79,
                'name' => 'Germany',
                'code' => 'DE',
                'calling_code' => '49',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 80,
                'name' => 'Ghana',
                'code' => 'GH',
                'calling_code' => '233',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 81,
                'name' => 'Gibraltar',
                'code' => 'GI',
                'calling_code' => '350',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 82,
                'name' => 'Greece',
                'code' => 'GR',
                'calling_code' => '30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 83,
                'name' => 'Greenland',
                'code' => 'GL',
                'calling_code' => '299',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 84,
                'name' => 'Grenada',
                'code' => 'GD',
                'calling_code' => '1 473',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 85,
                'name' => 'Guam',
                'code' => 'GU',
                'calling_code' => '1 671',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 86,
                'name' => 'Guatemala',
                'code' => 'GT',
                'calling_code' => '502',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 87,
                'name' => 'Guernsey',
                'code' => 'GG',
                'calling_code' => '44 1481',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 88,
                'name' => 'Guinea',
                'code' => 'GN',
                'calling_code' => '224',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 89,
                'name' => 'Guinea-Bissau',
                'code' => 'GW',
                'calling_code' => '245',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 90,
                'name' => 'Guyana',
                'code' => 'GY',
                'calling_code' => '592',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 91,
                'name' => 'Haiti',
                'code' => 'HT',
                'calling_code' => '509',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 92,
                'name' => 'Holy See (Vatican City State)',
                'code' => 'VA',
                'calling_code' => '379',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 93,
                'name' => 'Honduras',
                'code' => 'HN',
                'calling_code' => '504',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 94,
                'name' => 'Hong Kong',
                'code' => 'HK',
                'calling_code' => '852',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 95,
                'name' => 'Hungary',
                'code' => 'HU',
                'calling_code' => '36',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 96,
                'name' => 'Iceland',
                'code' => 'IS',
                'calling_code' => '354',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 97,
                'name' => 'India',
                'code' => 'IN',
                'calling_code' => '91',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 98,
                'name' => 'Indonesia',
                'code' => 'ID',
                'calling_code' => '62',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 99,
                'name' => 'Islamic Republic of Iran',
                'code' => 'IR',
                'calling_code' => '98',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 100,
                'name' => 'Iraq',
                'code' => 'IQ',
                'calling_code' => '964',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 101,
                'name' => 'Ireland',
                'code' => 'IE',
                'calling_code' => '353',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 102,
                'name' => 'Isle of Man',
                'code' => 'IM',
                'calling_code' => '44 1624',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 103,
                'name' => 'Israel',
                'code' => 'IL',
                'calling_code' => '972',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 104,
                'name' => 'Italy',
                'code' => 'IT',
                'calling_code' => '39',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 105,
                'name' => 'Jamaica',
                'code' => 'JM',
                'calling_code' => '1 658',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 106,
                'name' => 'Japan',
                'code' => 'JP',
                'calling_code' => '81',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 107,
                'name' => 'Jersey',
                'code' => 'JE',
                'calling_code' => '44 1534',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 108,
                'name' => 'Jordan',
                'code' => 'JO',
                'calling_code' => '962',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 109,
                'name' => 'Kazakhstan',
                'code' => 'KZ',
                'calling_code' => '76',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 110,
                'name' => 'Kenya',
                'code' => 'KE',
                'calling_code' => '254',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 111,
                'name' => 'Kiribati',
                'code' => 'KI',
                'calling_code' => '686',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 112,
                'name' => 'North Korea',
                'code' => 'KP',
                'calling_code' => '850',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 113,
                'name' => 'South Korea',
                'code' => 'KR',
                'calling_code' => '82',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 114,
                'name' => 'Kuwait',
                'code' => 'KW',
                'calling_code' => '965',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 115,
                'name' => 'Kyrgyzstan',
                'code' => 'KG',
                'calling_code' => '996',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 116,
                'name' => 'Lao People\'s Democratic Republic',
                'code' => 'LA',
                'calling_code' => '856',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 117,
                'name' => 'Latvia',
                'code' => 'LV',
                'calling_code' => '371',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 118,
                'name' => 'Lebanon',
                'code' => 'LB',
                'calling_code' => '961',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 119,
                'name' => 'Lesotho',
                'code' => 'LS',
                'calling_code' => '266',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 120,
                'name' => 'Liberia',
                'code' => 'LR',
                'calling_code' => '231',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 121,
                'name' => 'Libya',
                'code' => 'LY',
                'calling_code' => '218',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 122,
                'name' => 'Liechtenstein',
                'code' => 'LI',
                'calling_code' => '423',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 123,
                'name' => 'Lithuania',
                'code' => 'LT',
                'calling_code' => '370',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 124,
                'name' => 'Luxembourg',
                'code' => 'LU',
                'calling_code' => '352',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 125,
                'name' => 'Macao',
                'code' => 'MO',
                'calling_code' => '853',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 126,
                'name' => 'Republic of Macedonia',
                'code' => 'MK',
                'calling_code' => '389',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 127,
                'name' => 'Madagascar',
                'code' => 'MG',
                'calling_code' => '261',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 128,
                'name' => 'Malawi',
                'code' => 'MW',
                'calling_code' => '265',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 129,
                'name' => 'Malaysia',
                'code' => 'MY',
                'calling_code' => '60',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 130,
                'name' => 'Maldives',
                'code' => 'MV',
                'calling_code' => '960',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 131,
                'name' => 'Mali',
                'code' => 'ML',
                'calling_code' => '223',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 132,
                'name' => 'Malta',
                'code' => 'MT',
                'calling_code' => '356',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 133,
                'name' => 'Marshall Islands',
                'code' => 'MH',
                'calling_code' => '692',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 134,
                'name' => 'Martinique',
                'code' => 'MQ',
                'calling_code' => '596',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 135,
                'name' => 'Mauritania',
                'code' => 'MR',
                'calling_code' => '222',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 136,
                'name' => 'Mauritius',
                'code' => 'MU',
                'calling_code' => '230',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 137,
                'name' => 'Mexico',
                'code' => 'MX',
                'calling_code' => '52',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 138,
                'name' => 'Federated States of Micronesia',
                'code' => 'FM',
                'calling_code' => '691',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 139,
                'name' => 'Republic of Moldova',
                'code' => 'MD',
                'calling_code' => '373',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 140,
                'name' => 'Monaco',
                'code' => 'MC',
                'calling_code' => '377',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 141,
                'name' => 'Mongolia',
                'code' => 'MN',
                'calling_code' => '976',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 142,
                'name' => 'Montenegro',
                'code' => 'ME',
                'calling_code' => '382',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 143,
                'name' => 'Montserrat',
                'code' => 'MS',
                'calling_code' => '1 664',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 144,
                'name' => 'Morocco',
                'code' => 'MA',
                'calling_code' => '212',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 145,
                'name' => 'Mozambique',
                'code' => 'MZ',
                'calling_code' => '258',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 146,
                'name' => 'Myanmar',
                'code' => 'MM',
                'calling_code' => '95',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 147,
                'name' => 'Namibia',
                'code' => 'NA',
                'calling_code' => '264',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 148,
                'name' => 'Nauru',
                'code' => 'NR',
                'calling_code' => '674',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 149,
                'name' => 'Nepal',
                'code' => 'NP',
                'calling_code' => '977',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 150,
                'name' => 'Netherlands',
                'code' => 'NL',
                'calling_code' => '31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 151,
                'name' => 'New Zealand',
                'code' => 'NZ',
                'calling_code' => '64',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 152,
                'name' => 'Nicaragua',
                'code' => 'NI',
                'calling_code' => '505',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 153,
                'name' => 'Niger',
                'code' => 'NE',
                'calling_code' => '227',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 154,
                'name' => 'Nigeria',
                'code' => 'NG',
                'calling_code' => '234',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 155,
                'name' => 'Niue',
                'code' => 'NU',
                'calling_code' => '683',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 156,
                'name' => 'Norfolk Island',
                'code' => 'NF',
                'calling_code' => '672 3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 157,
                'name' => 'Northern Mariana Islands',
                'code' => 'MP',
                'calling_code' => '1 670',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 158,
                'name' => 'Norway',
                'code' => 'NO',
                'calling_code' => '47',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 159,
                'name' => 'Oman',
                'code' => 'OM',
                'calling_code' => '968',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 160,
                'name' => 'Pakistan',
                'code' => 'PK',
                'calling_code' => '92',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 161,
                'name' => 'Palau',
                'code' => 'PW',
                'calling_code' => '680',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 162,
                'name' => 'Palestine,
                State of',
                'code' => 'PS',
                'calling_code' => '970',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 163,
                'name' => 'Panama',
                'code' => 'PA',
                'calling_code' => '507',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 164,
                'name' => 'Papua New Guinea',
                'code' => 'PG',
                'calling_code' => '675',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 165,
                'name' => 'Paraguay',
                'code' => 'PY',
                'calling_code' => '595',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 166,
                'name' => 'Peru',
                'code' => 'PE',
                'calling_code' => '51',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 167,
                'name' => 'Philippines',
                'code' => 'PH',
                'calling_code' => '63',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 168,
                'name' => 'Pitcairn',
                'code' => 'PN',
                'calling_code' => '64',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 169,
                'name' => 'Poland',
                'code' => 'PL',
                'calling_code' => '48',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 170,
                'name' => 'Portugal',
                'code' => 'PT',
                'calling_code' => '351',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 171,
                'name' => 'Puerto Rico',
                'code' => 'PR',
                'calling_code' => '1 787',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 172,
                'name' => 'Qatar',
                'code' => 'QA',
                'calling_code' => '974',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 173,
                'name' => 'Romania',
                'code' => 'RO',
                'calling_code' => '40',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 174,
                'name' => 'Russian Federation',
                'code' => 'RU',
                'calling_code' => '7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 175,
                'name' => 'Rwanda',
                'code' => 'RW',
                'calling_code' => '250',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 176,
                'name' => 'Scotland',
                'code' => 'SLD',
                'calling_code' => '44',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 177,
                'name' => 'Saint Barthélemy',
                'code' => 'BL',
                'calling_code' => '590',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 178,
                'name' => 'Saint Kitts and Nevis',
                'code' => 'KN',
                'calling_code' => '1 869',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 179,
                'name' => 'Saint Lucia',
                'code' => 'LC',
                'calling_code' => '1 758',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 180,
                'name' => 'Saint Vincent and the Grenadines',
                'code' => 'VC',
                'calling_code' => '1 784',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 181,
                'name' => 'Samoa',
                'code' => 'WS',
                'calling_code' => '685',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 182,
                'name' => 'San Marino',
                'code' => 'SM',
                'calling_code' => '378',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 183,
                'name' => 'Sao Tome and Principe',
                'code' => 'ST',
                'calling_code' => '239',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 184,
                'name' => 'Saudi Arabia',
                'code' => 'SA',
                'calling_code' => '966',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 185,
                'name' => 'Senegal',
                'code' => 'SN',
                'calling_code' => '221',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 186,
                'name' => 'Serbia',
                'code' => 'RS',
                'calling_code' => '381',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 187,
                'name' => 'Seychelles',
                'code' => 'SC',
                'calling_code' => '248',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 188,
                'name' => 'Sierra Leone',
                'code' => 'SL',
                'calling_code' => '232',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 189,
                'name' => 'Singapore',
                'code' => 'SG',
                'calling_code' => '65',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 190,
                'name' => 'Sint Maarten',
                'code' => 'SX',
                'calling_code' => '1 721',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 191,
                'name' => 'Slovakia',
                'code' => 'SK',
                'calling_code' => '421',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 192,
                'name' => 'Slovenia',
                'code' => 'SI',
                'calling_code' => '386',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 193,
                'name' => 'Solomon Islands',
                'code' => 'SB',
                'calling_code' => '677',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 194,
                'name' => 'Somalia',
                'code' => 'SO',
                'calling_code' => '252',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 195,
                'name' => 'South Africa',
                'code' => 'ZA',
                'calling_code' => '27',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 196,
                'name' => 'South Sudan',
                'code' => 'SS',
                'calling_code' => '211',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 197,
                'name' => 'Spain',
                'code' => 'ES',
                'calling_code' => '34',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 198,
                'name' => 'Sri Lanka',
                'code' => 'LK',
                'calling_code' => '94',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 199,
                'name' => 'Sudan',
                'code' => 'SD',
                'calling_code' => '249',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 200,
                'name' => 'Suriname',
                'code' => 'SR',
                'calling_code' => '597',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 201,
                'name' => 'Swaziland',
                'code' => 'SZ',
                'calling_code' => '268',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 202,
                'name' => 'Sweden',
                'code' => 'SE',
                'calling_code' => '46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 203,
                'name' => 'Switzerland',
                'code' => 'CH',
                'calling_code' => '41',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 204,
                'name' => 'Syrian Arab Republic',
                'code' => 'SY',
                'calling_code' => '963',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 205,
                'name' => 'Taiwan',
                'code' => 'TW',
                'calling_code' => '886',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 206,
                'name' => 'Tajikistan',
                'code' => 'TJ',
                'calling_code' => '992',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 207,
                'name' => 'United Republic of Tanzania',
                'code' => 'TZ',
                'calling_code' => '255',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 208,
                'name' => 'Thailand',
                'code' => 'TH',
                'calling_code' => '66',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 209,
                'name' => 'Timor-Leste',
                'code' => 'TL',
                'calling_code' => '670',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 210,
                'name' => 'Togo',
                'code' => 'TG',
                'calling_code' => '228',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 211,
                'name' => 'Tokelau',
                'code' => 'TK',
                'calling_code' => '690',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 212,
                'name' => 'Tonga',
                'code' => 'TO',
                'calling_code' => '676',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 213,
                'name' => 'Trinidad and Tobago',
                'code' => 'TT',
                'calling_code' => '1 868',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 214,
                'name' => 'Tunisia',
                'code' => 'TN',
                'calling_code' => '216',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 215,
                'name' => 'Turkey',
                'code' => 'TR',
                'calling_code' => '90',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 216,
                'name' => 'Turkmenistan',
                'code' => 'TM',
                'calling_code' => '993',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 217,
                'name' => 'Turks and Caicos Islands',
                'code' => 'TC',
                'calling_code' => '1 649',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 218,
                'name' => 'Tuvalu',
                'code' => 'TV',
                'calling_code' => '688',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 219,
                'name' => 'Uganda',
                'code' => 'UG',
                'calling_code' => '256',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 220,
                'name' => 'Ukraine',
                'code' => 'UA',
                'calling_code' => '380',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 221,
                'name' => 'United Arab Emirates',
                'code' => 'AE',
                'calling_code' => '971',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 222,
                'name' => 'United Kingdom',
                'code' => 'GB',
                'calling_code' => '44',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 223,
                'name' => 'United States',
                'code' => config('base.default_country_select'),
                'calling_code' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 224,
                'name' => 'Uruguay',
                'code' => 'UY',
                'calling_code' => '598',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 225,
                'name' => 'Uzbekistan',
                'code' => 'UZ',
                'calling_code' => '998',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 226,
                'name' => 'Vanuatu',
                'code' => 'VU',
                'calling_code' => '678',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 227,
                'name' => 'Bolivarian Republic of Venezuela',
                'code' => 'VE',
                'calling_code' => '58',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 228,
                'name' => 'Viet Nam',
                'code' => 'VN',
                'calling_code' => '84',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 229,
                'name' => 'Virgin Islands, British',
                'code' => 'VG',
                'calling_code' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 230,
                'name' => 'Virgin Islands, U.S.',
                'code' => 'VI',
                'calling_code' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 231,
                'name' => 'Yemen',
                'code' => 'YE',
                'calling_code' => '967',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 232,
                'name' => 'Zambia',
                'code' => 'ZM',
                'calling_code' => '260',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 233,
                'name' => 'Zimbabwe',
                'code' => 'ZW',
                'calling_code' => '263',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 234,
                'name' => 'Wales',
                'code' => 'WL',
                'calling_code' => '44',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('countries')->insert($countries);

        $this->enableForeignKeys();
    }
}
