<?php

$constants = [
    'ADMIN_DASHBOARD' => 'admin.dashboard',
    'ADMIN_FREELANCER_LIST' => 'admin.freelancer.*',
    'ADMIN_EMPLOYER_LIST' => 'admin.employer.*',
    'ADMIN_JOB_LIST' => 'admin.job.*',
    'ADMIN_SETTING_LIST' => 'admin.setting.*',
    'TYPE_DROP_PROJECT' => 'dropzone-project',
    'TYPE_FREELANCER' => 'freelancer',
    'TYPE_EMPLOYER' => 'employer',
    'TYPE_JOB' => 'job',
    'IS_ACTIVE' => '1',
    'TYPE_USER' => 'user',
    'USER_DASHBOARD' => 'frontend.user.dashboard',
    'FREELANCER_SETTING' => 'frontend.freelancer.setting',
    'FREELANCER_INDEX' => 'frontend.freelancer.index',
    'EMPLOYER_SETTING' => 'frontend.employer.setting',
    'EMPLOYER_INDEX' => 'frontend.employer.index',
    'FREELANCER_JOB_APPLICATIONS' => 'frontend.freelancer.job-applications',
    'FREELANCER_JOB_SAVED' => 'frontend.freelancer.job-saved',
    'FREELANCER_JOB_DONE' => 'frontend.freelancer.job-done',
    'FREELANCER_JOB_DETAIL' => 'frontend.freelancer.job-detail',
    'CHAT_MESSAGE_ROUTE' => 'frontend.message.index',
    'CREATE_CHAT_MESSAGE_ROUTE' => 'frontend.message.store',
    'USER_CHAT_MESSAGE_ROUTE' => 'frontend.message.chat',
    'IS_USER' => false,
    'IS_APPLIED' => 1,
    'STATUS_OPEN' => 1,
    'JOBS_TABLE_NAME' => 'jobs',
    'JOB_APPLICATIONS_TABLE_NAME' => 'job_applications',
    'MESSAGES_TABLE_NAME' => 'messages',
    'USERS_TABLE_NAME' => 'users',
    'VERIFY_MIN_NUMBER' => 1000,
    'VERIFY_MAX_NUMBER' => 9999,
    'VERIFY_TIME_EXPIRATION_TOKEN' => 5,
    'PREVIOUS' => 'previous',
    'NEXT' => 'next',
    'FIRST_PAGE' => 1,
    'TYPE_SORT_ASC' => 'ASC',
    'TYPE_SORT_DESC' => 'DESC',
    'INACTIVE_STAR' => 0,
    'ACTIVE_STAR' => 1,
    'HALF_PART_STAR' => 0.5,
    'POINT_REVIEW_ARRAY' => [0, 1, 2, 3, 4, 5],
    'FIND_FREELANCER' => 'frontend.employer.find-freelancer',
    'USER_REVIEW' => 'user_id',
    'JOB_REVIEW' => 'job_id',
    'EMPLOYER_CREATE_JOB' => 'frontend.employer.jobs.create',
    'FRONTEND_LOGIN' => 'frontend.auth.login',
    'SAVED_FREELANCER_ROUTER' => 'frontend.employer.saved.freelancer',
    'SAVED_JOB_ROUTER' => 'frontend.employer.saved.job',
    'SAVED_FREELANCER' => 'freelancer',
    'SAVED_JOB' => 'job',
    'JOB_INDEX' => 'frontend.employer.jobs.index',
    'FREELANCER_PAYMENT_INDEX' => 'frontend.freelancer.payments.index',
    'EMPLOYER_PAYMENT_INDEX' => 'frontend.employer.payments.index',
    'STATUS_JOB_APPLICATION_ARRAY' => [0, 2, 3],
    'NOTIFICATION_INDEX_SUFFIX' => 'frontend.notifications.index',
    'TYPE_DELETE_NOTIFICATION' => 'notification',
    'FREELANCER_JOB_DONE_PREVIEW' => 'frontend.freelancer.jobs.done.preview',
    'UN_READ_MESSAGE' => 0,
    'READ_MESSAGE' => 1,
    'TYPE_MESSAGE_TEXT' => 1,
    'TYPE_MESSAGE_FILE' => 2,
    'LOAD_MORE_QUANTITY' => 30,
    'CHUNK_COLLECTION_USER' => 1000,
    'ESCROW_ACCOUNT_TYPE' => [
        'create_new_account' => 0,
        'account_exists' => 1
    ]
];

foreach ($constants as $key => $constant) {
    if (!defined($key)) {
        define($key, $constant);
    }
}
